### PR TITLE
fix wrong number of arguments

### LINKED ISSUE #669: Running docker image with TLS fails
```
*** FATAL CONFIG FILE ERROR (Redis 7.2.4) ***
Reading the configuration file, at line 2
>>> 'protected-mode "no" ""'
wrong number of arguments
```

### PR DESCRIPTION
**Pull request by dudizimber**
Fix #669

### CODE REVIEW

File: build/docker/run.sh [hunk 1]
```diff
@@ -11,7 +11,7 @@ fi
 if [ ${TLS:-0} -eq 1 ]
 then
     /FalkorDB/build/docker/gen-certs.sh
-    redis-server --protected-mode no ${REDIS_ARGS:-""} \
+    redis-server --protected-mode no ${REDIS_ARGS} \
```
Comment (AviAvni) [inline build/docker/run.sh:14]: there is more like this in line 20 and 23

Comment (dudizimber) [reply build/docker/run.sh:14]: They weren't causing issues as they are at the end of the line, but I'll remove them nonetheless

**Review by AviAvni — APPROVED** [review]
