### PR TITLE
treat zero length traversals as variable length traversals

### LINKED ISSUE #478: Crash when MATCH path of length 0
ref: https://github.com/RedisGraph/RedisGraph/issues/3213

I execute a query on my empty RedisGraph and get a crash.

Redis version:7.2.0
RedisGraph version: v2.12.10
operating system: windows 11
API：Cypher version 9
error message:"Reached the max retries per request limit (which is 1). Refer to "maxRetriesPerRequest" option for details."

To reproduce:
CREATE (:L)-[:T]->()
MATCH (a:L)<-[*0..0]-(b) WHERE a is not null and id(b)>=0 RETURN count(a)

Actual behavior:
The query failed and the redisgraph container exited abnormally with the error message.

```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
98099:M 28 Oct 2023 18:24:23.180 # Redis 7.2.2 crashed by signal: 11, si_code: 1
98099:M 28 Oct 2023 18:24:23.180 # Accessing address: (nil)
98099:M 28 Oct 2023 18:24:23.180 # Crashed running the instruction at: 0x7ff130b83776

------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(+0x183776)[0x7ff130b83776]

Backtrace:
/lib/x86_64-linux-gnu/libc.so.6(+0x3c460)[0x7ff130a3c460]
/lib/x86_64-linux-gnu/libc.so.6(+0x183776)[0x7ff130b83776]
./bin/linux-x64-release/src/falkordb.so(_GraphContext_GetLabelID+0x41)[0x7ff12e26efa1]
./bin/linux-x64-release/src/falkordb.so(GraphContext_GetSchema+0x14)[0x7ff12e26f1f4]
./bin/linux-x64-release/src/falkordb.so(buildMatchOpTree+0x1ee)[0x7ff12e24cbde]
./bin/linux-x64-release/src/falkordb.so(ExecutionPlan_PopulateExecutionPlan+0x77)[0x7ff12e24b317]
./bin/linux-x64-release/src/falkordb.so(ExecutionPlan_FromTLS_AST+0x128)[0x7ff12e24b488]
./bin/linux-x64-release/src/falkordb.so(ExecutionCtx_FromQuery+0x12f)[0x7ff12e240e0f]
./bin/linux-x64-release/src/falkordb.so(_query+0x56)[0x7ff12e240716]
./bin/linux-x64-release/src/falkordb.so(+0x29991f)[0x7ff12e29991f]
/lib/x86_64-linux-gnu/libc.so.6(+0x8f6ba)[0x7ff130a8f6ba]
/lib/x86_64-linux-gnu/libc.so.6(+0x11e0d0)[0x7ff130b1e0d0]
```

### PR DESCRIPTION
**Pull request by swilly22**
Resolves #478

Queries such as:
```cypher
MATCH (a)-[*0]->(b) RETURN a, b
```
Treat the zero length edge as a variable length edge of length 0.
By doing so the pattern is matched by the `Conditional Variable Length Traverse` operation, matching only the source node.

### CODE REVIEW

File: src/graph/entities/qg_edge.c [hunk 1]
```diff
@@ -70,12 +70,19 @@ QGEdge *QGEdge_Clone
 	return e;
 }
 
+// returns true if edge represents a variable length path
+// e.g. ()-[*]->()
+// note: a zero length edge: ()-[*0]->() is considered a variable length edge
```
Comment (AviAvni) [inline src/graph/entities/qg_edge.c:75]: why?

**Review by AviAvni — CHANGES_REQUESTED** [review]

File: src/graph/entities/qg_edge.c (hunk 1 above)
Comment (swilly22) [reply src/graph/entities/qg_edge.c:75]: We would like to treat zero length edges as variable length edges, this way our var-len traversal will be used and only the source node will be matched.
